name: Terrform CI (Choice)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform Action"
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy
      confirm:
        description: "Confirm destructive action (required for destroy and apply)"
        required: false
        default: 'no'
        options:
          - yes
          - no

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: us-east-1


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terrform
        uses: hashicorp/setup-terraform@v3

      - name: Terrform init
        run: terraform init
      
      - name: Terrform Validate
        run: terraform validate
      
      - name: Terraform plan
        if: ${{github.event.inputs.action == "plan" || github.event.inputs.action == "apply"}}
        run: terraform plan -out=tfplan
      
      - name: Terraform apply
        if: ${{github.event.inputs.action == 'apply' && github.event.inputs.confirm == 'yes'}}
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destory (Plan)
        if: ${{github.event.input.action == 'destroy'}}
        run: terraform plan -destroy -out=destroyplan
      
      - name: Terraform Destory
        if: ${{github.event.inputs.action == 'destroy' && github.event.inputs.confirm == 'yes'}}
        run: terraform destroy -auto-approve destroyplan